# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24e75f8f202a9ee14cb5e3513a9012d8c847b36f80e9b336dc81fcefb8fb8bd05ee19bea92fb41706f29029a5938e4f0ca0c7c74b677414c9f2d49514129463e

test:
  secret_key_base: 530bf866e08a670c1d1ab10e005eb3eddf2f59b03e7109baf9d1eaf096e39fd429c4101cb43f40ef267d682884b3fb5f4ea156ade13e16b5720d48aaf04dd6aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
